image: python:latest

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - pip install poetry
  - poetry config virtualenvs.in-project true


pages:
  script:
    - cd cours
    - poetry install
    - poetry run python build.py --werror
    - mv build/html ../public/
  artifacts:
    paths:
      - public
  cache:
    paths:
      - cours/.venv
      - .cache/pip
  only:
    - master
