image: python:latest



before_script:
  - pip install poetry


pages:
  script:
    - cd cours
    - poetry install
    - poetry run python build.py --werror
    - mv build/html ../public/
  artifacts:
    paths:
      - public
  only:
    - master
